"""Decision and risk-control utilities for CrossViewGate."""

from .ontology import (
    DEFAULT_ONTOLOGY_PATH,
    AggregationRule,
    CostMatrix,
    DerivedLabel,
    DerivedScheme,
    OntologyUsageError,
    OntologyValidationError,
    OperationalOntology,
    build_cost_matrix,
    load_ontology,
    load_operational_ontology,
    validate_ontology,
)
from .risk_control import (
    DEFAULT_REVIEW_BUDGETS,
    CalibrationResult,
    LockedTestResult,
    assert_disjoint_protocol_splits,
    bounded_classification_loss,
    build_per_sample_decisions,
    calibrate_threshold,
    critical_target_mask,
    evaluate_locked_threshold,
    one_sided_risk_upper_bound,
    recall_at_review_budgets,
    risk_coverage_curve,
)

__all__ = [
    "DEFAULT_ONTOLOGY_PATH",
    "DEFAULT_REVIEW_BUDGETS",
    "AggregationRule",
    "CalibrationResult",
    "CostMatrix",
    "DerivedLabel",
    "DerivedScheme",
    "LockedTestResult",
    "OntologyUsageError",
    "OntologyValidationError",
    "OperationalOntology",
    "assert_disjoint_protocol_splits",
    "bounded_classification_loss",
    "build_cost_matrix",
    "build_per_sample_decisions",
    "calibrate_threshold",
    "critical_target_mask",
    "evaluate_locked_threshold",
    "load_ontology",
    "load_operational_ontology",
    "one_sided_risk_upper_bound",
    "recall_at_review_budgets",
    "risk_coverage_curve",
    "validate_ontology",
]
from .active_view import (
    ActiveViewCache,
    ActiveViewMLP,
    DEFAULT_OPERATIONAL_COST,
    Standardizer,
    build_selector_features,
    build_state_features,
    entropy,
    expected_operational_cost,
    farthest_available_sector,
    load_active_view_cache,
    realized_operational_cost,
    reveal_sector,
    softmax,
)
from .active_view_utility import (
    AdaptiveActionBatch,
    bayes_operational_action_and_risk,
    build_candidate_geometry_features,
    build_candidate_utility_features,
    select_adaptive_actions,
    target_conditioned_soft_loss,
)

__all__ += [
    "AdaptiveActionBatch",
    "ActiveViewCache",
    "ActiveViewMLP",
    "DEFAULT_OPERATIONAL_COST",
    "Standardizer",
    "bayes_operational_action_and_risk",
    "build_candidate_geometry_features",
    "build_candidate_utility_features",
    "build_selector_features",
    "build_state_features",
    "entropy",
    "expected_operational_cost",
    "farthest_available_sector",
    "load_active_view_cache",
    "realized_operational_cost",
    "reveal_sector",
    "select_adaptive_actions",
    "softmax",
    "target_conditioned_soft_loss",
]
